### GET all users
GET http://localhost:3000/api/users
Content-Type: application/json; charset=utf-8

### GET user by id
GET http://localhost:3000/api/users/id/6
Content-Type: application/json; charset=utf-8

### GET user by email
GET http://localhost:3000/api/users/email/toto@mail.com
Content-Type: application/json; charset=utf-8

### POST create user
POST http://localhost:3000/api/users
Content-Type: application/json; charset=utf-8

{
    "username": "newUser",
    "email": "newuser@mail.co",
    "password": "SuperMotDePasse@1"
}

### UPDATE user
PATCH http://localhost:3000/api/users/7
Content-Type: application/json; charset=utf-8

{
    "email": "tata@mail.com"
}

### DELETE user
DELETE http://localhost:3000/api/users/3
Content-Type: application/json; charset=utf-8